/*

https://jenkins.io/doc/tutorials/build-a-java-app-with-maven/
https://jenkins.io/doc/book/pipeline/docker/
https://funnelgarden.com/sonarqube-jenkins-docker/

https://medium.com/@rosaniline/setup-sonarqube-with-jenkins-declarative-pipeline-75bccdc9075f
https://stackoverflow.com/questions/48557886/how-to-execute-sonarqube-scanner-in-jenkins-declarative-pipeline-without-maven-a

https://stackoverflow.com/questions/42817169/jenkins-trigger-builds-remotely-authentication-token-option-missing

Pending things to fix:
- Do not add sonar.java.binaries option here
- Create a docker-compose file to set up the containers

dv8-console arch-report -paramsFile archreport.properties

apk add eudev

Trigger: curl -I -X POST "http://admin:11c135301ff1ab896872af14b2ad65303e@localhost:8080/job/JenkinsSonarqube/build?token=J6SiKjpEaLqiU7WuQlMIZ1qlMrml5fhM"

*/
pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }  
        
        /*
        stage('Sonarqube analysis') {
            environment {
                SONAR_SCANNER_OPTS = "-Xmx2g -Dsonar.projectKey=Test -Dsonar.login=202b6aef450f839353fc0f087248c4a8a566c9e1 -Dsonar.java.binaries=/var/jenkins_home/workspace/JenkinsSonarqube@2/target/classes"
            } 
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh "/var/jenkins_home/sonar-scanner/sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dproject.settings=sonar-project.properties"
                }
            }
        }
        */
        
        

        stage('DV8 analysis') {
            steps {
                sh 'curl http://172.18.0.3:8080/preprocessor?directory=/var/jenkins_home/workspace/JenkinsSonarqube@2'
            }
        }  

    }
}
